name: CI
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        ruby: ['2.4', '2.5', '2.6', '2.7']
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: gem install bundler
    - run: bundle install
    - run: bundle exec rspec
    - run: bundle exec rubocop
    - run: bundle exec rake build
